version: "3"
services:
  report_backend:
    image: report-backend:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: report-backend
    environment:
      SERVER_MODE: "debug"
      SERVER_PORT: ":8005"
      DATABASE_CLIENT: "mysql"
      DATABASE_MAX_IDLE: 10
      DATABASE_MAX_LIFE_TIME: "1h"
      DATABASE_MAX_OPEN_CONN: 100
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "1qaz2wsx"
      DATABASE_HOST: "10.99.1.93"
      DATABASE_DB: "report"
      DATABASE_PORT: "3306"
      DATABASE_PARAMS: "charset=utf8mb4&parseTime=True&loc=Asia%2fTaipei"
      EMAIL_USER: ""
      EMAIL_PASSWORD: ""
      EMAIL_SENDER: ""
      EMAIL_HOST: ""
      EMAIL_PORT: ""
      FILES_MIGRATIONS_FILE: ""
      FILES_TEMPLATE_FILE: ""
      FILES_SCREENSHOT_FILE: ""
      FILES_HTML_FILE: ""
      FILES_REPORT_FILE: ""
      FILES_LOG_PATH: ""
      FILES_LOGO_FILE: ""
      FILES_FONT_FILE: "."
    ports:
      - "8005:8005"
    volumes:
      - ./report:/app/files/report_files
      - ./screenshot:/app/files/screenshot_files
      - ./log_record:/app/log_record




